"""
AquaSynex — Chronological Streaming Entity Clustering (Phase 2.4)
SIH26146: AI-Powered Monitoring & Analysis of Bitcoin Transaction Traffic

Implements chronological streaming address clustering using:
1. Multi-Input (Common Spending) Heuristic:
   Addresses co-spent as inputs to the same transaction are inferred to be
   controlled by the same behavioral entity.
2. Change Address Heuristic:
   One-time change outputs generated by a transaction are linked back to the
   spending entity.

TEMPORAL LEAKAGE RULE:
Clustering state is evolved chronologically. For each transaction T:
- Inspect the entity state *before* transaction T.
- Extract historical features: hist_cluster_id, hist_cluster_size, hist_cluster_tx_count.
- Only *then* apply unions and update cluster transaction counts.
This ensures future transactions never alter the cluster features of past transactions.

TERMINOLOGY NOTE:
All references denote "inferred behavioral clusters" or "address clusters",
never claiming definitive proof of real-world identity.
"""

import os
from typing import Dict, List, Set, Tuple, Any, Optional
import pandas as pd
import duckdb

class UnionFind:
    """
    Disjoint-set data structure with path compression and union by rank,
    augmented to track member sets and cluster activity counts.
    """
    def __init__(self):
        self.parent: Dict[str, str] = {}
        self.rank: Dict[str, int] = {}
        self.cluster_members: Dict[str, Set[str]] = {}
        self.cluster_tx_count: Dict[str, int] = {}

    def find(self, item: str) -> str:
        if item not in self.parent:
            self.parent[item] = item
            self.rank[item] = 0
            self.cluster_members[item] = {item}
            self.cluster_tx_count[item] = 0
            return item

        # Path compression
        path = []
        curr = item
        while self.parent[curr] != curr:
            path.append(curr)
            curr = self.parent[curr]
        for node in path:
            self.parent[node] = curr
        return curr

    def get_size(self, item: str) -> int:
        root = self.find(item)
        return len(self.cluster_members.get(root, {item}))

    def get_tx_count(self, item: str) -> int:
        root = self.find(item)
        return self.cluster_tx_count.get(root, 0)

    def union(self, item1: str, item2: str) -> str:
        root1 = self.find(item1)
        root2 = self.find(item2)

        if root1 == root2:
            return root1

        # Union by rank
        if self.rank[root1] < self.rank[root2]:
            root1, root2 = root2, root1

        self.parent[root2] = root1
        if self.rank[root1] == self.rank[root2]:
            self.rank[root1] += 1

        # Merge member sets and tx counts
        self.cluster_members[root1].update(self.cluster_members.pop(root2, set()))
        self.cluster_tx_count[root1] += self.cluster_tx_count.pop(root2, 0)

        return root1

    def increment_tx_count(self, root: str):
        actual_root = self.find(root)
        self.cluster_tx_count[actual_root] = self.cluster_tx_count.get(actual_root, 0) + 1


class TemporalEntityClusterer:
    """
    Applies Multi-Input and Change heuristics chronologically over transaction streams.
    """
    def __init__(self):
        self.uf = UnionFind()

    def process_transactions_chronologically(
        self,
        df_tx: pd.DataFrame,
        df_in: pd.DataFrame,
        df_out: pd.DataFrame
    ) -> pd.DataFrame:
        """
        Process transactions in strict chronological order, extracting historical
        cluster features BEFORE applying unions.
        """
        tx_id_col = "transaction_id" if "transaction_id" in df_tx.columns else "txid"
        in_tx_col = "transaction_id" if "transaction_id" in df_in.columns else "txid"
        out_tx_col = "transaction_id" if "transaction_id" in df_out.columns else "txid"
        in_addr_col = "input_address" if "input_address" in df_in.columns else "address"
        out_addr_col = "output_address" if "output_address" in df_out.columns else "address"

        # 1. Sort transactions strictly chronologically (timestamp ascending, then txid for tie-breaking)
        df_tx_sorted = df_tx.sort_values(
            by=["timestamp_epoch_sec", tx_id_col],
            ascending=[True, True]
        ).reset_index(drop=True)

        # 2. Group inputs and outputs by transaction_id for fast lookup
        inputs_by_tx: Dict[str, List[str]] = {}
        if not df_in.empty:
            for _, r in df_in.iterrows():
                txid = str(r[in_tx_col]).strip().lower()
                addr = str(r[in_addr_col]).strip()
                if addr and addr not in ("None", "nan"):
                    inputs_by_tx.setdefault(txid, []).append(addr)

        change_by_tx: Dict[str, List[str]] = {}
        if not df_out.empty:
            for _, r in df_out.iterrows():
                txid = str(r[out_tx_col]).strip().lower()
                addr = str(r[out_addr_col]).strip()
                is_chg = bool(r["is_change"]) if "is_change" in r and pd.notna(r["is_change"]) else False
                if is_chg and addr and addr not in ("None", "nan"):
                    change_by_tx.setdefault(txid, []).append(addr)

        # Reset UnionFind state
        self.uf = UnionFind()
        feature_records = []

        # 3. Stream transactions chronologically
        for _, tx_row in df_tx_sorted.iterrows():
            txid = str(tx_row[tx_id_col]).strip().lower()
            in_addrs = inputs_by_tx.get(txid, [])
            chg_addrs = change_by_tx.get(txid, [])

            # STEP A: Extract historical features BEFORE mutating cluster state
            if in_addrs:
                primary_addr = in_addrs[0]
                hist_root = self.uf.find(primary_addr)
                # Check if this address had already been seen prior to this transaction
                # If it was just initialized in self.uf.find, its tx_count was 0 and member set was {primary_addr}
                hist_size = self.uf.get_size(primary_addr)
                hist_tx_cnt = self.uf.get_tx_count(primary_addr)
                cluster_id_str = f"cluster_{hist_root}"
            else:
                # Coinbase or inputless transaction
                cluster_id_str = "cluster_unknown"
                hist_size = 0
                hist_tx_cnt = 0

            feature_records.append({
                "transaction_id": txid,
                "hist_cluster_id": cluster_id_str,
                "hist_cluster_size": int(hist_size),
                "hist_cluster_tx_count": int(hist_tx_cnt)
            })

            # STEP B: Apply Multi-Input (Common Spending) Heuristic
            # Union all input addresses in this transaction
            active_root = None
            if in_addrs:
                base_addr = in_addrs[0]
                active_root = self.uf.find(base_addr)
                for other_addr in in_addrs[1:]:
                    active_root = self.uf.union(active_root, other_addr)

            # STEP C: Apply Change Heuristic
            # Union any change output addresses into the input cluster
            if active_root is not None and chg_addrs:
                for chg_addr in chg_addrs:
                    active_root = self.uf.union(active_root, chg_addr)

            # STEP D: Update cluster transaction count for future transactions
            if active_root is not None:
                self.uf.increment_tx_count(active_root)

        features_df = pd.DataFrame(feature_records)
        return features_df

    def get_final_cluster_summary(self) -> pd.DataFrame:
        """
        Extract post-hoc summary of address-to-cluster mappings.
        """
        rows = []
        for addr in self.uf.parent.keys():
            root = self.uf.find(addr)
            rows.append({
                "address": addr,
                "cluster_root": root,
                "cluster_size": self.uf.get_size(root),
                "cluster_tx_count": self.uf.get_tx_count(root)
            })
        return pd.DataFrame(rows)
